version: '3'

volumes:
  wordpress_db:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mariadb
      o: bind

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_db:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
    stop_grace_period: 1s
    env_file: .env
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    volumes:
      - wordpress_db:/var/www/html
    networks:
      - inception
    restart: always
    env_file: .env
    stop_grace_period: 1s
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    stop_grace_period: 1s
    env_file: .env
    volumes:
      - "mariadb:/var/lib/mysql"
    networks:
      - inception
    restart: always
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    ports:
      - 8000:8000
    networks:
      - inception
    restart: always
    stop_grace_period: 1s
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    stop_grace_period: 1s
    ports:
      - 6379:6379
    depends_on:
      - wordpress
    networks:
      - inception
  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor
    ports:
      - "8080:8080"
    stop_grace_period: 1s
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
  portfolio:
    container_name: portfolio
    build: ./requirements/bonus/portfolio
    ports:
      - "4200:4200"
networks:
  inception:
    driver: bridge

